[
  {
    restaurant_name: "Pizza Ability",
    restaurant_description:
      "Just think of all the pizzabilities you can have here. World famous pizza and afforable rates.",
    restaurant_location_address:
      "Kitchener Complex, 809 French Road, Singapore 200809",
    restaurant_location_city: "Singapore",
    restaurant_location_country: "Singapore",
    restaurant_location_lat: 1.3083087,
    restaurant_location_long: 103.8620241,
    restaurant_image: [
      "https://i.ibb.co/bbwKyfb/photo-1561666383-903d234a16b4-ixlib-rb-1-2.jpg",
      "https://i.ibb.co/PGxY2nQ/photo-1490717064594-3bd2c4081693-ixlib-rb-1-2.jpg",
    ],
    restaurant_opening_hours: "Open from 9 AM to 2 PM",
    restaurant_facilities: ["Parking", "Pet Friendly"],
    restaurant_cuisine: ["Italian", "Pizza"],
    restaurant_cost: 3,
    restaurant_start_date: "01-12-2021",
    restaurant_end_date: "28-02-2022",
    restaurant_start_time: "09:00",
    restaurant_end_time: "14:00",
    restaurant_average_seating_time: 60,
    restaurant_max_table_one: 3,
    restaurant_max_table_two: 4,
    restaurant_max_table_three: 3,
    restaurant_max_table_four: 8,
    restaurant_max_table_five: 6,
  },
  {
    restaurant_name: "It Laksa Good",
    restaurant_description:
      "Because Laksa has never looked this good. An original family recepie from 1889",
    restaurant_location_address: "803 Horne Road, Singapore 200807",
    restaurant_location_city: "Singapore",
    restaurant_location_country: "Singapore",
    restaurant_location_lat: 1.3083248,
    restaurant_location_long: 103.8607028,
    restaurant_image: [
      "https://i.ibb.co/vsvb2JL/photo-1632057153728-9ee20b615f8d-ixlib-rb-1-2.jpg",
      "https://i.ibb.co/5LvWt9q/photo-1633271332313-04df64c0105b-ixlib-rb-1-2.jpg",
    ],
    restaurant_opening_hours: "Open from 9 AM to 2 PM",
    restaurant_facilities: ["Parking", "Free-Wifi"],
    restaurant_cuisine: ["Malaysian", "Asian"],
    restaurant_cost: 2,
    restaurant_start_date: "01-12-2021",
    restaurant_end_date: "28-02-2022",
    restaurant_start_time: "09:00",
    restaurant_end_time: "14:00",
    restaurant_average_seating_time: 60,
    restaurant_max_table_one: 3,
    restaurant_max_table_two: 5,
    restaurant_max_table_three: 2,
    restaurant_max_table_four: 6,
    restaurant_max_table_five: 2,
  },
  {
    restaurant_name: "Nitrous Cafe",
    restaurant_description:
      "When you need get somewhere fast and you are furious, come to Nitro to get your boost. Because here we are all Family.",
    restaurant_location_address: "2 Kitchener Road, Singapore 208581",
    restaurant_location_city: "Singapore",
    restaurant_location_country: "Singapore",
    restaurant_location_lat: 1.3078477,
    restaurant_location_long: 103.8590937,
    restaurant_image: [
      "https://i.ibb.co/8D6mM15/car-born-cafe-jb-10.jpg",
      "https://i.ibb.co/dQm3FLg/photo-1619641084194-07e262dd12ee-ixlib-rb-1-2.jpg",
    ],
    restaurant_opening_hours: "Open from 9 AM to 2 PM",
    restaurant_facilities: ["Parking", "Family Friendly"],
    restaurant_cuisine: ["International", "Cafe"],
    restaurant_cost: 4,
    restaurant_start_date: "01-12-2021",
    restaurant_end_date: "28-02-2022",
    restaurant_start_time: "09:00",
    restaurant_end_time: "14:00",
    restaurant_average_seating_time: 90,
    restaurant_max_table_one: 3,
    restaurant_max_table_two: 4,
    restaurant_max_table_three: 3,
    restaurant_max_table_four: 8,
    restaurant_max_table_five: 5,
  },
  {
    restaurant_name: "Wee Yu Mee Pok",
    restaurant_description:
      "Michelin Star Chef Yu Wee has wined and dined at the best restaurants. Now he has returned to Singapore to open his very own Mee Pok Restaurant.",
    restaurant_location_address: "Aperia, Kallang Avenue, Singapore 339416",
    restaurant_location_city: "Singapore",
    restaurant_location_country: "Singapore",
    restaurant_location_lat: 1.3104193,
    restaurant_location_long: 103.8635313,
    restaurant_image: [
      "https://i.ibb.co/Jz9sZdT/1200px-Simple-mee-pok.jpg",
      "https://i.ibb.co/PTkh1Sp/photo.jpg",
    ],
    restaurant_opening_hours: "Open from 12 PM to 9 PM",
    restaurant_facilities: ["Wheelchair Access", "Family Friendly"],
    restaurant_cuisine: ["Chinese", "Teochew"],
    restaurant_cost: 3,
    restaurant_start_date: "01-12-2021",
    restaurant_end_date: "28-02-2022",
    restaurant_start_time: "12:00",
    restaurant_end_time: "21:00",
    restaurant_average_seating_time: 60,
    restaurant_max_table_one: 3,
    restaurant_max_table_two: 4,
    restaurant_max_table_three: 3,
    restaurant_max_table_four: 8,
    restaurant_max_table_five: 5,
  },
  {
    restaurant_name: "Arabian Nights",
    restaurant_description:
      "Be mesmerised by the wonderful selection of Middle Eastern delights, made from the freshest ingredients with love.",
    restaurant_location_address: "20 Hamilton Road, Singapore 209201",
    restaurant_location_city: "Singapore",
    restaurant_location_country: "Singapore",
    restaurant_location_lat: 1.311199,
    restaurant_location_long: 103.8611239,
    restaurant_image: [
      "https://i.ibb.co/XpSwj8d/photo-1541754202-9eb0e8c13b6c-ixlib-rb-1-2.jpg",
      "https://i.ibb.co/PYcJpkf/photo-1611765438425-519200c7ec2e-ixlib-rb-1-2.jpg",
    ],
    restaurant_opening_hours: "Open from 12 PM to 9 PM",
    restaurant_facilities: ["Parking", "Family Friendly"],
    restaurant_cuisine: ["Middle Eastern", "Halal"],
    restaurant_cost: 4,
    restaurant_start_date: "01-12-2021",
    restaurant_end_date: "28-02-2022",
    restaurant_start_time: "12:00",
    restaurant_end_time: "21:00",
    restaurant_average_seating_time: 60,
    restaurant_max_table_one: 3,
    restaurant_max_table_two: 5,
    restaurant_max_table_three: 3,
    restaurant_max_table_four: 9,
    restaurant_max_table_five: 5,
  },
  {
    restaurant_name: "Burger Spree",
    restaurant_description:
      "Burgers, Sandwiches and Sliders - we have got them all! When you are free, eat at Burger Spree",
    restaurant_location_address:
      "Jalan Besar Plaza, Kitchener Road, Singapore 208510",
    restaurant_location_city: "Singapore",
    restaurant_location_country: "Singapore",
    restaurant_location_lat: 1.3086478,
    restaurant_location_long: 103.8580674,
    restaurant_image: [
      "https://i.ibb.co/tzqynj8/photo-1593462386344-bc7ffba51a1e-ixlib-rb-1-2.png",
      "https://i.ibb.co/jLTWrx4/photo-1600891964751-dc0cc8611e47-ixlib-rb-1-2.jpg",
    ],
    restaurant_opening_hours: "Open from 10 AM to 6 PM",
    restaurant_facilities: ["Parking", "Family Friendly"],
    restaurant_cuisine: ["Burgers", "American"],
    restaurant_cost: 4,
    restaurant_start_date: "01-12-2021",
    restaurant_end_date: "28-02-2022",
    restaurant_start_time: "10:00",
    restaurant_end_time: "18:00",
    restaurant_average_seating_time: 60,
    restaurant_max_table_one: 3,
    restaurant_max_table_two: 5,
    restaurant_max_table_three: 3,
    restaurant_max_table_four: 9,
    restaurant_max_table_five: 5,
  },
  {
    restaurant_name: "Noti Roti",
    restaurant_description:
      "Whether you want to get dinner or a late night supper, find your favourite Indian meals at Noti Roti!",
    restaurant_location_address:
      "Little India, Upper Dickson Road, Singapore 207491",
    restaurant_location_city: "Singapore",
    restaurant_location_country: "Singapore",
    restaurant_location_lat: 1.3085541,
    restaurant_location_long: 103.856497,
    restaurant_image: [
      "https://i.ibb.co/xLqHtGC/photo-1536305030588-45dc07a2a372-ixlib-rb-1-2.jpg",
      "https://i.ibb.co/cJW5WLv/photo-1617692855027-33b14f061079-ixlib-rb-1-2.jpg",
    ],
    restaurant_opening_hours: "Open from 6 PM to 11 PM",
    restaurant_facilities: ["Parking", "Free Wi-Fi"],
    restaurant_cuisine: ["South Asian", "Indian"],
    restaurant_cost: 3,
    restaurant_start_date: "01-12-2021",
    restaurant_end_date: "28-02-2022",
    restaurant_start_time: "18:00",
    restaurant_end_time: "23:00",
    restaurant_average_seating_time: 60,
    restaurant_max_table_one: 3,
    restaurant_max_table_two: 2,
    restaurant_max_table_three: 3,
    restaurant_max_table_four: 9,
    restaurant_max_table_five: 6,
  },
  {
    restaurant_name: "Crab! So Good",
    restaurant_description:
      "Serving Singapore's favourite crab dishes from lunch to dinner! Try our Alaskan Crabs and you'll be sayin 'Crab! So good!'",
    restaurant_location_address: "Jalan Besar, Singapore 208913",
    restaurant_location_city: "Singapore",
    restaurant_location_country: "Singapore",
    restaurant_location_lat: 1.3096609,
    restaurant_location_long: 103.8582163,
    restaurant_image: [
      "https://i.ibb.co/2KMw38r/CHILLI-CRABS.jpg",
      "https://i.ibb.co/3YC59ZS/d4f865c70d914d9eb37e37e64ec8b8e2-301178-490134630997003-1283745360-n.jpg",
    ],
    restaurant_opening_hours: "Open from 11 AM to 11 PM",
    restaurant_facilities: ["Parking", "Wheelchair Access"],
    restaurant_cuisine: ["Singpaorean", "Seafood"],
    restaurant_cost: 4,
    restaurant_start_date: "01-12-2021",
    restaurant_end_date: "28-02-2022",
    restaurant_start_time: "11:00",
    restaurant_end_time: "23:00",
    restaurant_average_seating_time: 60,
    restaurant_max_table_one: 3,
    restaurant_max_table_two: 4,
    restaurant_max_table_three: 3,
    restaurant_max_table_four: 9,
    restaurant_max_table_five: 6,
  },
  {
    restaurant_name: "Squid Gamjajeon",
    restaurant_description:
      "Our famous Squid Gamjajeon comes with a dalgona candy. If you can break shape out in 5 mins you get 5% off!",
    restaurant_location_address: "Hanjin Building, Myeong-dong, Seoul, 04534",
    restaurant_location_city: "Seoul",
    restaurant_location_country: "South Korea",
    restaurant_location_lat: 37.56268,
    restaurant_location_long: 126.9813202,
    restaurant_image: [
      "https://i.ibb.co/K9W3yb8/potato-pancake-piece.jpg",
      "https://i.ibb.co/5jxKMv8/Dalgona-Candy-Recipe-Card.jpg",
    ],
    restaurant_opening_hours: "Open from 9 AM to 12 PM",
    restaurant_facilities: ["Parking", "Free Wi-Fi"],
    restaurant_cuisine: ["Korean", "Asian"],
    restaurant_cost: 4,
    restaurant_start_date: "01-12-2021",
    restaurant_end_date: "28-02-2022",
    restaurant_start_time: "09:00",
    restaurant_end_time: "11:00",
    restaurant_average_seating_time: 60,
    restaurant_max_table_one: 3,
    restaurant_max_table_two: 4,
    restaurant_max_table_three: 3,
    restaurant_max_table_four: 9,
    restaurant_max_table_five: 6,
  },
  {
    restaurant_name: "UFO Burger",
    restaurant_description:
      "Our UFO Burgers are out of this world! Packaged in such a way that there will be no spillage!",
    restaurant_location_address:
      "Aloft Seoul Myeongdong, Myeong-dong, Seoul 04530",
    restaurant_location_city: "Seoul",
    restaurant_location_country: "South Korea",
    restaurant_location_lat: 37.5622634,
    restaurant_location_long: 126.9819612,
    restaurant_image: [
      "https://i.ibb.co/YTrGGRD/UFO-Burger-FB-Cover.jpg",
      "hhttps://i.ibb.co/s6NFHsv/photo-1551039226-821e296bdd9d-ixlib-rb-1-2.jpg",
    ],
    restaurant_opening_hours: "Open from 12 PM to 9 PM",
    restaurant_facilities: ["Parking", "Free Wi-Fi"],
    restaurant_cuisine: ["Burger", "American"],
    restaurant_cost: 3,
    restaurant_start_date: "01-12-2021",
    restaurant_end_date: "28-02-2022",
    restaurant_start_time: "12:00",
    restaurant_end_time: "21:00",
    restaurant_average_seating_time: 60,
    restaurant_max_table_one: 3,
    restaurant_max_table_two: 4,
    restaurant_max_table_three: 3,
    restaurant_max_table_four: 9,
    restaurant_max_table_five: 6,
  },
  {
    restaurant_name: "Blankpink Cafe",
    restaurant_description:
      "An unofficial cafe to celebrate everything Blackpink. Enjoy our brunch deals while you discuss about you favorite Blackpink member. Answer, they are all great.",
    restaurant_location_address: "Hotel Lotte, Myeong-dong, Seoul 04523",
    restaurant_location_city: "Seoul",
    restaurant_location_country: "South Korea",
    restaurant_location_lat: 37.5652075,
    restaurant_location_long: 126.9807209,
    restaurant_image: [
      "https://i.ibb.co/q13zQft/blackpink-pop-up-store3.jpg",
      "https://i.ibb.co/8BzzG7M/337535dd5db5655fbe3b1e03b6e7d219.jpg",
    ],
    restaurant_opening_hours: "Open from 9 AM to 2 PM",
    restaurant_facilities: ["Wheelchair Access", "Free Wi-Fi"],
    restaurant_cuisine: ["International", "Cafe"],
    restaurant_cost: 3,
    restaurant_start_date: "01-12-2021",
    restaurant_end_date: "28-02-2022",
    restaurant_start_time: "09:00",
    restaurant_end_time: "14:00",
    restaurant_average_seating_time: 60,
    restaurant_max_table_one: 3,
    restaurant_max_table_two: 4,
    restaurant_max_table_three: 3,
    restaurant_max_table_four: 9,
    restaurant_max_table_five: 6,
  },
  {
    restaurant_name: "BB Im Bap",
    restaurant_description:
      "For all you love birds out there, BB Im Bap now serves the traiditional Bibimbap in a couples package at half price!",
    restaurant_location_address: "CM, Myeong-dong, Seoul 04535",
    restaurant_location_city: "Seoul",
    restaurant_location_country: "South Korea",
    restaurant_location_lat: 37.5612529,
    restaurant_location_long: 126.9844334,
    restaurant_image: [
      "https://i.ibb.co/jWM8hQx/photo-1498654896293-37aacf113fd9-ixlib-rb-1-2.jpg",
      "https://i.ibb.co/N631VJh/photo-1553163147-622ab57be1c7-ixlib-rb-1-2.jpg",
    ],
    restaurant_opening_hours: "Open from 10 AM to 6 PM",
    restaurant_facilities: ["Family Friendly", "Free Wi-Fi"],
    restaurant_cuisine: ["Korean", "Asian"],
    restaurant_cost: 3,
    restaurant_start_date: "01-12-2021",
    restaurant_end_date: "28-02-2022",
    restaurant_start_time: "10:00",
    restaurant_end_time: "18:00",
    restaurant_average_seating_time: 60,
    restaurant_max_table_one: 2,
    restaurant_max_table_two: 8,
    restaurant_max_table_three: 5,
    restaurant_max_table_four: 5,
    restaurant_max_table_five: 6,
  },
  {
    restaurant_name: "Behind The Spaghetti",
    restaurant_description:
      "Behind The Spaghetti aims to serve the best traditional Italian dishes that will remind you of your Nona. No relation to the famous boyband BTS. Stop asking.",
    restaurant_location_address: "97 Toegye-ro, Myeong-dong, Seoul 04631",
    restaurant_location_city: "Seoul",
    restaurant_location_country: "South Korea",
    restaurant_location_lat: 37.5610391,
    restaurant_location_long: 126.9824703,
    restaurant_image: [
      "https://i.ibb.co/HrnnYd7/photo-1585002400872-ec6f400e56b8-ixlib-rb-1-2.jpg",
      "https://i.ibb.co/hMJQM0W/photo-1533777324565-a040eb52facd-ixlib-rb-1-2.jpg",
    ],
    restaurant_opening_hours: "Open from 6 PM to 11 PM",
    restaurant_facilities: ["Family Friendly", "Free Wi-Fi"],
    restaurant_cuisine: ["Italian", "Scilian"],
    restaurant_cost: 4,
    restaurant_start_date: "01-12-2021",
    restaurant_end_date: "28-02-2022",
    restaurant_start_time: "18:00",
    restaurant_end_time: "23:00",
    restaurant_average_seating_time: 60,
    restaurant_max_table_one: 2,
    restaurant_max_table_two: 8,
    restaurant_max_table_three: 3,
    restaurant_max_table_four: 6,
    restaurant_max_table_five: 6,
  },
  {
    restaurant_name: "Top Of The Evening",
    restaurant_description:
      "Breakfast food sold in the evening because breakfast food is the best food. Endorsed by Leslie Knope and Ron Swanson.",
    restaurant_location_address:
      "Gilbeys Yard, London, NW1 8HB, United Kingdom",
    restaurant_location_city: "London",
    restaurant_location_country: "United Kingdom",
    restaurant_location_lat: 51.5407332,
    restaurant_location_long: -0.1485398,
    restaurant_image: [
      "https://i.ibb.co/4VCX8RM/photo-1611601184963-9d1de9b79ff3-ixlib-rb-1-2.jpg",
      "https://i.ibb.co/Fn3rTDL/photo-1504754524776-8f4f37790ca0-ixlib-rb-1-2.jpg",
    ],
    restaurant_opening_hours: "Open from 6 PM to 11 PM",
    restaurant_facilities: ["Family Friendly", "Free Wi-Fi"],
    restaurant_cuisine: ["Breakfast", "British"],
    restaurant_cost: 3,
    restaurant_start_date: "01-12-2021",
    restaurant_end_date: "28-02-2022",
    restaurant_start_time: "18:00",
    restaurant_end_time: "23:00",
    restaurant_average_seating_time: 60,
    restaurant_max_table_one: 2,
    restaurant_max_table_two: 8,
    restaurant_max_table_three: 3,
    restaurant_max_table_four: 6,
    restaurant_max_table_five: 6,
  },
];
