[
    {
        "restaurant_name": "Pizza Ability",
        "restaurant_description": "Just think of all the pizzabilities you can have here. World famous pizza and afforable rates.",
        "restaurant_location_address": "Kitchener Complex, 809 French Road, Singapore 200809" ,
        "restaurant_location_city": "Singapore",
        "restaurant_location_country": "Singapore",
        "restaurant_location_lat": 1.3083087,
        "restaurant_location_long": 103.8620241,
        "restaurant_image": ["https://bigthink.com/wp-content/uploads/2017/04/origin-88.jpg", "https://i2-prod.mirror.co.uk/incoming/article13387061.ece/ALTERNATES/s1200b/2_Childrens-hands-taking-pizza-slices-out-or-box.jpg"],
        "restaurant_opening_hours": "Open from 9 AM to 2 PM",
        "restaurant_facilities": ["Parking", "Pet Friendly"],
        "restaurant_cuisine": ["Italian", "Pizza"],
        "restaurant_cost": 3,
        "restaurant_start_date": "01-12-2021",
        "restaurant_end_date": "28-02-2022",
        "restaurant_start_time": "09:00",
        "restaurant_end_time": "14:00",
        "restaurant_average_seating_time": 60,
        "restaurant_max_table_one": 3,
        "restaurant_max_table_two": 4,
        "restaurant_max_table_three": 3,
        "restaurant_max_table_four": 8,
        "restaurant_max_table_five": 6
    },
    {
        "restaurant_name": "It Laksa Good",
        "restaurant_description": "Because Laksa has never looked this good. An original family recepie from 1889",
        "restaurant_location_address": "803 Horne Road, Singapore 200807" ,
        "restaurant_location_city": "Singapore",
        "restaurant_location_country": "Singapore",
        "restaurant_location_lat": 1.3083248,
        "restaurant_location_long": 103.8607028,
        "restaurant_image": ["https://www.getteaspoon.com/source/upload/blog/long_desc/209/big-normal-%281%29.jpg", "https://www.getteaspoon.com/source/upload/blog/long_desc/209/super-big-%282%29.jpg"],
        "restaurant_opening_hours": "Open from 9 AM to 2 PM",
        "restaurant_facilities": ["Parking", "Free-Wifi"],
        "restaurant_cuisine": ["Chinese", "Asian"],
        "restaurant_cost": 2,
        "restaurant_start_date": "01-12-2021",
        "restaurant_end_date": "28-02-2022",
        "restaurant_start_time": "09:00",
        "restaurant_end_time": "14:00",
        "restaurant_average_seating_time": 60,
        "restaurant_max_table_one": 3,
        "restaurant_max_table_two": 5,
        "restaurant_max_table_three": 2,
        "restaurant_max_table_four": 6,
        "restaurant_max_table_five": 2
    },
    {
        "restaurant_name": "Nitrous Cafe",
        "restaurant_description": "When you need get somewhere fast and you are furious, come to Nitro to get your boost. Because here we are all Family.",
        "restaurant_location_address": "2 Kitchener Road, Singapore 208581" ,
        "restaurant_location_city": "Singapore",
        "restaurant_location_country": "Singapore",
        "restaurant_location_lat": 1.3078477,
        "restaurant_location_long": 103.8590937,
        "restaurant_image": ["https://eatbook.sg/wp-content/uploads/2016/11/car-born-cafe-jb-10.jpg", "https://assets3.thrillist.com/v1/image/2827042/1200x630/flatten;crop_down;webp=auto;jpeg_quality=70"],
        "restaurant_opening_hours": "Open from 9 AM to 2 PM",
        "restaurant_facilities": ["Parking", "Family Friendly"],
        "restaurant_cuisine": ["International", "Cafe"],
        "restaurant_cost": 4,
        "restaurant_start_date": "01-12-2021",
        "restaurant_end_date": "28-02-2022",
        "restaurant_start_time": "09:00",
        "restaurant_end_time": "14:00",
        "restaurant_average_seating_time": 90,
        "restaurant_max_table_one": 3,
        "restaurant_max_table_two": 4,
        "restaurant_max_table_three": 3,
        "restaurant_max_table_four": 8,
        "restaurant_max_table_five": 5
    },
    {
        "restaurant_name": "Wee Yu Mee Pok",
        "restaurant_description": "Michelin Star Chef Yu Wee has wined and dined at the best restaurants. Now he has returned to Singapore to open his very own Mee Pok Restaurant.",
        "restaurant_location_address": "Aperia, Kallang Avenue, Singapore 339416" ,
        "restaurant_location_city": "Singapore",
        "restaurant_location_country": "Singapore",
        "restaurant_location_lat": 1.3104193,
        "restaurant_location_long": 103.8635313,
        "restaurant_image": ["https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Simple_mee_pok.jpg/1200px-Simple_mee_pok.jpg", "https://img-global.cpcdn.com/recipes/48052451/1200x630cq70/photo.jpg"],
        "restaurant_opening_hours": "Open from 12 PM to 9 PM",
        "restaurant_facilities": ["Wheelchair Access", "Family Friendly"],
        "restaurant_cuisine": ["Chinese", "Teochew"],
        "restaurant_cost": 3,
        "restaurant_start_date": "01-12-2021",
        "restaurant_end_date": "28-02-2022",
        "restaurant_start_time": "12:00",
        "restaurant_end_time": "21:00",
        "restaurant_average_seating_time": 60,
        "restaurant_max_table_one": 3,
        "restaurant_max_table_two": 4,
        "restaurant_max_table_three": 3,
        "restaurant_max_table_four": 8,
        "restaurant_max_table_five": 5
    },
    {
        "restaurant_name": "Arabian Nights",
        "restaurant_description": "Be mesmerised by the wonderful selection of Middle Eastern delights, made from the freshest ingredients with love.",
        "restaurant_location_address": "20 Hamilton Road, Singapore 209201" ,
        "restaurant_location_city": "Singapore",
        "restaurant_location_country": "Singapore",
        "restaurant_location_lat": 1.311199,
        "restaurant_location_long": 103.8611239,
        "restaurant_image": ["https://img.jakpost.net/c/2016/06/03/2016_06_03_5777_1464956271._large.jpg", "https://static.thehoneycombers.com/wp-content/uploads/sites/2/2015/07/mediterranean-restaurants-in-Singapore.png"],
        "restaurant_opening_hours": "Open from 12 PM to 9 PM",
        "restaurant_facilities": ["Parking", "Family Friendly"],
        "restaurant_cuisine": ["Middle Eastern", "Halal"],
        "restaurant_cost": 4,
        "restaurant_start_date": "01-12-2021",
        "restaurant_end_date": "28-02-2022",
        "restaurant_start_time": "12:00",
        "restaurant_end_time": "21:00",
        "restaurant_average_seating_time": 60,
        "restaurant_max_table_one": 3,
        "restaurant_max_table_two": 5,
        "restaurant_max_table_three": 3,
        "restaurant_max_table_four": 9,
        "restaurant_max_table_five": 5
    },
    {
        "restaurant_name": "Burger Spree",
        "restaurant_description": "Burgers, Sandwiches and Sliders - we have got them all! When you are free, eat at Burger Spree",
        "restaurant_location_address": "Jalan Besar Plaza, Kitchener Road, Singapore 208510" ,
        "restaurant_location_city": "Singapore",
        "restaurant_location_country": "Singapore",
        "restaurant_location_lat": 1.3086478,
        "restaurant_location_long": 103.8580674,
        "restaurant_image": ["https://mir-s3-cdn-cf.behance.net/project_modules/1400/dc9cf566811953.5b22ce31f3821.jpg", "https://eatbook.sg/wp-content/uploads/2020/01/Best-Burger-Singapore-Hammees-beef-1024x683.jpg"],
        "restaurant_opening_hours": "Open from 10 AM to 6 PM",
        "restaurant_facilities": ["Parking", "Family Friendly"],
        "restaurant_cuisine": ["Burgers", "American"],
        "restaurant_cost": 4,
        "restaurant_start_date": "01-12-2021",
        "restaurant_end_date": "28-02-2022",
        "restaurant_start_time": "10:00",
        "restaurant_end_time": "18:00",
        "restaurant_average_seating_time": 60,
        "restaurant_max_table_one": 3,
        "restaurant_max_table_two": 5,
        "restaurant_max_table_three": 3,
        "restaurant_max_table_four": 9,
        "restaurant_max_table_five": 5
    },
    {
        "restaurant_name": "Noti Roti",
        "restaurant_description": "Whether you want to get dinner or a late night supper, find your favourite Indian meals at Noti Roti!",
        "restaurant_location_address": "Little India, Upper Dickson Road, Singapore 207491" ,
        "restaurant_location_city": "Singapore",
        "restaurant_location_country": "Singapore",
        "restaurant_location_lat": 1.3085541,
        "restaurant_location_long": 103.8564970,
        "restaurant_image": ["https://images.thrillophilia.com/image/upload/s--4gzHZqo_--/c_fill,g_center,h_642,q_auto,w_1280/f_auto,fl_strip_profile/v1/images/photos/000/161/993/original/1563255602_fd1b2139d10d83372eda87e4fd439605.jpg.jpg", "https://cdn.vox-cdn.com/thumbor/0wyFEegdQbbBq5wsGq-wzrDpgAo=/0x0:1441x1170/1200x900/filters:focal(606x470:836x700)/cdn.vox-cdn.com/uploads/chorus_image/image/56206415/BombayBeach2.29.jpeg"],
        "restaurant_opening_hours": "Open from 6 PM to 11 PM",
        "restaurant_facilities": ["Parking", "Free Wi-Fi"],
        "restaurant_cuisine": ["South Asian", "Indian"],
        "restaurant_cost": 3,
        "restaurant_start_date": "01-12-2021",
        "restaurant_end_date": "28-02-2022",
        "restaurant_start_time": "18:00",
        "restaurant_end_time": "23:00",
        "restaurant_average_seating_time": 60,
        "restaurant_max_table_one": 3,
        "restaurant_max_table_two": 2,
        "restaurant_max_table_three": 3,
        "restaurant_max_table_four": 9,
        "restaurant_max_table_five": 6
    },
    {
        "restaurant_name": "Crab! So Good",
        "restaurant_description": "Serving Singapore's favourite crab dishes from lunch to dinner! Try our Alaskan Crabs and you'll be sayin 'Crab! So good!'",
        "restaurant_location_address": "Jalan Besar, Singapore 208913" ,
        "restaurant_location_city": "Singapore",
        "restaurant_location_country": "Singapore",
        "restaurant_location_lat": 1.3096609,
        "restaurant_location_long": 103.8582163,
        "restaurant_image": ["https://www.bestinsingapore.co/wp-content/uploads/2019/07/CHILLI-CRABS.jpg", "https://d3h1lg3ksw6i6b.cloudfront.net/media/image/2017/10/27/d4f865c70d914d9eb37e37e64ec8b8e2_301178_490134630997003_1283745360_n.jpg"],
        "restaurant_opening_hours": "Open from 11 AM to 11 PM",
        "restaurant_facilities": ["Parking", "Wheelchair Access"],
        "restaurant_cuisine": ["Singpaorean", "Seafood"],
        "restaurant_cost": 4,
        "restaurant_start_date": "01-12-2021",
        "restaurant_end_date": "28-02-2022",
        "restaurant_start_time": "11:00",
        "restaurant_end_time": "23:00",
        "restaurant_average_seating_time": 60,
        "restaurant_max_table_one": 3,
        "restaurant_max_table_two": 4,
        "restaurant_max_table_three": 3,
        "restaurant_max_table_four": 9,
        "restaurant_max_table_five": 6
    },
    {
        "restaurant_name": "Squid Gamjajeon",
        "restaurant_description": "Our famous Squid Gamjajeon comes with a dalgona candy. If you can break shape out in 5 mins you get 5% off!",
        "restaurant_location_address": "Hanjin Building, Myeong-dong, Seoul, 04534" ,
        "restaurant_location_city": "Seoul",
        "restaurant_location_country": "South Korea",
        "restaurant_location_lat": 37.5626800,
        "restaurant_location_long": 126.9813202,
        "restaurant_image": ["https://www.maangchi.com/wp-content/uploads/2016/11/potato-pancake-piece.jpg", "https://preppykitchen.com/wp-content/uploads/2021/10/Dalgona-Candy-Recipe-Card.jpg"],
        "restaurant_opening_hours": "Open from 11 AM to 11 PM",
        "restaurant_facilities": ["Parking", "Free Wi-Fi"],
        "restaurant_cuisine": ["Korean", "Asian"],
        "restaurant_cost": 4,
        "restaurant_start_date": "01-12-2021",
        "restaurant_end_date": "28-02-2022",
        "restaurant_start_time": "11:00",
        "restaurant_end_time": "23:00",
        "restaurant_average_seating_time": 60,
        "restaurant_max_table_one": 3,
        "restaurant_max_table_two": 4,
        "restaurant_max_table_three": 3,
        "restaurant_max_table_four": 9,
        "restaurant_max_table_five": 6
    },

]